---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.4.54
      pullPolicy: IfNotPresent

    env:
      TZ: "America/New_York"

    service:
      main:
        annotations:
          coredns.io/hostname: unifi
          traefik.ingress.kubernetes.io/service.serversscheme: https
          metallb.universe.tf/allow-shared-ip: unifi-shared-ip
        type: LoadBalancer
        externalIPs:
          - ${CLUSTER_LB_UNIFI}
        externalTrafficPolicy: Local
        ports:
          stun:
            enabled: false
          syslog:
            enabled: false
          discovery:
            enabled: false
      udp:
        enabled: true
        annotations:
          metallb.universe.tf/allow-shared-ip: unifi-shared-ip
        type: LoadBalancer
        externalIPs:
          - ${CLUSTER_LB_UNIFI}
        externalTrafficPolicy: Local
        ports:
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - "unifi.${SECRET_DOMAIN}"
            secretName: "unifi-${SECRET_DOMAIN//./-}-tls"

    persistence:
      data:
        enabled: true
        existingClaim: unifi-config

    resources:
      requests:
        memory: 2Gi
        cpu: 100m
