apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DqL08Uuk1upcrziI/yJkCg==,iv:AVW/Ut25KcYxWL+ZsFQVNCMHhwa0Mui1krfGFHfaANg=,tag:C/Bo48tr2SB5vbl6p2n/GQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:+gZS5+6/83ifwxIOaTeBL5DvKJy9qTamORUMtMDtRpH/doU96g==,iv:5LwkjpHG+Fq75xkLM0GGBS521Eu6PuPAbjjqdJj+Nps=,tag:eTDp15lD1yrQATf9wxLQDw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:n44acrchZUYtcQ9QHvuT,iv:BpQollyXjkI8thZO3JxiyztRfXejCGcJeuYVKb3RYnI=,tag:G3TGqh2RamJo7K1J5dooWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzd6g8hl928w3l8tch8vntwhmv6zxanspe3xg43z4sa08lx36yqsvty85u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb3paK1RQZFRTM1hIb0hq
            UHBPcC9ETitrMVgxQ2FZVSsxb1kydEY0UTFnCjZGbzJwM2VKb1RmRUUvNDViWXc3
            bUdpLzFKMHI0UzZCOElMN3JGdHJvY1kKLS0tIE0rSjAzQzhqTWEvcERIa1E3dDVK
            bFRQVGFnbzRiRmpUZTY1S3VFY2UrdVEKONz1h1aVZD1rjgGgDHzq4Q5kffFgAPTW
            ohYyfb1VAIUM86rjtTrPtflo62jJzChJSYJFTcQkWa20jgKeYLOItw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T21:13:38Z"
    mac: ENC[AES256_GCM,data:T6DA0dhqZ5Oq7BN4k+GV1NE/h9Tyi3qpzohxmo/ezc/jj5eCmXN3ATHVdtUwG520JBQX+P5At0OwtXDg9BddPv5NY2vhW+vSVnN2AmQQUTPX1i+Iwh+fwOYnS+NO/QQh9lOnXXe33cOuiB2vtrp2kZ7WVqYV9Vh9Ncy3nnVGi2g=,iv:GXYBkJ6Df0vpMV5RQy7RvDNjTvX2eXtTZ0CEgJV4uOQ=,tag:Z2m3weAWbASkRYvYacl68Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
