apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZVEzIBhOGWF9cRdFQ3sbe9TrKD6BmJzQk8/CTQpEHC5J/1YNnvZ2+A==,iv:2bsj5GgxpbFWLwkNNsRBBZU8MFCGYulLJtCbi3wOG9U=,tag:qJGiuz0xel/rk2LPYL31iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzd6g8hl928w3l8tch8vntwhmv6zxanspe3xg43z4sa08lx36yqsvty85u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYnN3WVVnZlNYT0d2RmVI
            Szc1NitublNkNEZtQ0p0aCtNSFovZkFRakNjCmtkblBEdFN2ell2TEdTbEtySGlD
            VzNLQVpYcVNZczVPa2g2bkRvMEd3dGsKLS0tIGsra04rK1AybEp3VjRkcW1BMHho
            aER3bTVIc3VORDdWcHc0K2VEblJtMVkK4A9q687bCrjsPPkeyRONKz3s6MSK4Xkn
            hoT4GSQULxrrfjecPWunAOCsGsd21nfFjvPRGrNnIPPZYpUF+6/b6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-31T16:05:20Z"
    mac: ENC[AES256_GCM,data:QQUxXQeVwWU8Ax2KO6nZYutEiLTG7OCnmzP8GE4DWT01Ysi2d4Afjoza+zkWvgLyuZGgbthcmNDmlqrTfLC8f+hKt/YiuvCksituIjnE84hAAdyroaB+JflIcuCt6h+IOJKmwdPLN2Zi16tcVB7AqmDROm8AIH7Mn9K/VpNLs/g=,iv:HnkYSgtPl04qmrtEcE1VFRtAA9mrcMFZsKuKzTMrgGs=,tag:q52DOU6zavmPA2Pr3IH+2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
