apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hcxXI67k8lWovbYN69E0TDrHvOHi+YvoV8q3KYGXpqnY5VqY4FhwjQ==,iv:ECJOICKnl7YWv5Qf88ZNcQmr/NwLRWfRbueFmJ4bPxE=,tag:NP27sQMoqzdlLu2M4d4Shw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzd6g8hl928w3l8tch8vntwhmv6zxanspe3xg43z4sa08lx36yqsvty85u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNmg1T05qSHBXcXplWEZ4
            MUVTMGM3dS83Z0dCVVpvbldHbmtsYzY5Z21ZCnFwNzNzYXFIaWJJMDNiMHdGTkx5
            ZHNPZEo3bmgyNGpQdmtLc3FLSDRVbDAKLS0tIEJwWVBPZ3Z1bmtpcG9taTRmc3ov
            YzRzWXRvK2ZmSUlhMzVKcnJXZGdvR00KHTj9zoFFT4DtQ+j9IbIiYNquBL3xFlhu
            OKPGNkRPDX3jp/m8tcq8dgIvVFGSCAyHDsbhVzBOrq90Whvwshyq+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T21:13:38Z"
    mac: ENC[AES256_GCM,data:Uq9AktkAgva4NYEuL5o4/w5EEsa0ohh771PnRS/TFCufPJZAoB8UXFNfjelmpvpdm53EpqDAonXG5J4sYM63VnbLxD7otsesYSvxCROqTGhfTmZdtlcHx2nCUAJWoHPgG1x5lsdggS1GeSFVx6zuJTVI7pq25RZ+lGiE3pF2/gs=,iv:F/+s+oS6uxPMH3as42VI56vq1gGiyqN1Pxk11Rw/IQg=,tag:awp4tm/t4Z/ZUCFCoWLLWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
