---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hdhr-dvr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    hostNetwork: true
    # podAnnotations:
    #   k8s.v1.cni.cncf.io/networks: '[
    #       { "name": "home-network",
    #         "ips": [ "192.168.1.26/24" ],
    #         "gateway": [ "192.168.1.1" ]
    #       }]'
    image:
      repository: demonrik/hdhrdvr-docker
      tag: 0.2.4
      pullPolicy: Always
    env:
      DVRUI_PORT: &port 8080
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "dvrui.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      dvrdata:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.1.5"
            path: /hdhrdvr/dvrdata
        mountPath: /dvrdata
      dvrrec:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.1.5"
            path: /hdhrdvr/dvrrec
        mountPath: /dvrrec
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 250Mi
    #   limits:
    #     memory: 6000Mi
