apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdhr-dvr
  labels:
    app: hdhr-dvr
spec:
  selector:
    matchLabels:
      app: hdhr-dvr
  serviceName: hdhr-dvr
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        labels: {}
        annotations: {}
        name: dvrrec
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 300Gi
        storageClassName: nfs.fs01
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        labels: {}
        annotations: {}
        name: dvrdata
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
        storageClassName: nfs.fs01
  template:
    metadata:
      labels:
        app: hdhr-dvr
    spec:
      hostNetwork: true
      containers:
        - name: hdhr-dvr
          image: demonrik/hdhrdvr-docker
          volumeMounts:
            - name: dvrrec
              mountPath: /dvrrec
            - name: dvrdata
              mountPath: /dvrdata
