apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:l1Ef2TNsJeSvn59C1vsVBTFAnF9jontNOru4DFfm0KANotVCtA7fFmB+AOAbD4s7Dvlqbz+oI9fjM7X9,iv:k2gDxPE+bKiv4pzsbNXzfKF49lQ4EY1GaDPJFLm42Do=,tag:Kxt89tmlbd2u0wN/bFUvTQ==,type:str]
    username: ENC[AES256_GCM,data:hkB01Ak=,iv:RPZNRzCWdYmdJJ8C0Scs2uEoBYve0/76gR91lAlYfQ8=,tag:fXMm2N6jCuMxdptGOdm7Mg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzd6g8hl928w3l8tch8vntwhmv6zxanspe3xg43z4sa08lx36yqsvty85u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWDV1UXRZYU84WEpseGRB
            WUtxR01pb3hQZy9FWGE2UTRGZ0NJNk5yUERRCnpEblVnY1dYd2k2VFVycSt6aHl4
            M0lwY1NBK01XTzVDc1BIRlNhV2MwRHcKLS0tIDI0RlRMRmFUcytUVTNPeEp1bUZh
            ampOL1duU0JWSXp4QWlNREZBZmRGT3cKOmpqFJrxgJ2Nu7GpMNveYodqm43L2V9j
            NbvuZwnvbVum3NM5bOKf/ydAhXhFs6Or6136IBr2dtV1enwmaRfaiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T18:44:47Z"
    mac: ENC[AES256_GCM,data:OsGUmhvkEEs/LYt7PoUh8+04mktWT8zxCiuC5CdglOQEwBcom66+qCFLs+12yQ9zrJ+G5zOF6KA++K4D5KMJekjEg8mX//G0Zm0Vvc0lI53ALtAHYuWgylZZ1Ks7mJI1MxOadokgpU50tHVHd0M5JaJQyy47gUZ5eEQ9W0JsNfo=,iv:/0C/sYxCIJW2Je19Xj2d+6kY9Q/1AFkX765B+iB6CKw=,tag:liNC1yLbKUlQ/60ciRXZAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
