apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:XYjfWo+YB9MyfI9g8NRrt8vuJRrzvZEIh33P4zKRdkT4PcaH3qg4I71WU4nJ1G0RsdEJPbMCALgkQR2t,iv:iGka65WuyttixBk1/GGHLxT0RHOBKQ9vCAGejRIf+dA=,tag:7INsx8JPvQ+TjEdNFABBnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzd6g8hl928w3l8tch8vntwhmv6zxanspe3xg43z4sa08lx36yqsvty85u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWDV1UXRZYU84WEpseGRB
            WUtxR01pb3hQZy9FWGE2UTRGZ0NJNk5yUERRCnpEblVnY1dYd2k2VFVycSt6aHl4
            M0lwY1NBK01XTzVDc1BIRlNhV2MwRHcKLS0tIDI0RlRMRmFUcytUVTNPeEp1bUZh
            ampOL1duU0JWSXp4QWlNREZBZmRGT3cKOmpqFJrxgJ2Nu7GpMNveYodqm43L2V9j
            NbvuZwnvbVum3NM5bOKf/ydAhXhFs6Or6136IBr2dtV1enwmaRfaiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T12:43:45Z"
    mac: ENC[AES256_GCM,data:udLkZOxWpTFvCpCz0PMgUXLDetcRjqT8bObSabg3RNu1VickcfG5Knc4wsqHPY9RefbO6YPnqXyFWQvDQ9WrYG0ZcJDeGhW8bc6hA0PkQjJCDHuF6OFsH3yxNDqBa9vT0yScWspIvldlrlaW+ezY69wtzueUbYVklI5m1qyVcZg=,iv:sUJnj3j8Ivwbnv8093FJKBC+qi4RebtHV+TVOSqnWZU=,tag:NpUSgwqbtH++QRA9eo7XQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
