---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: ""
  METALLB_LB_RANGE: "192.168.1.10-192.168.1.29"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.20"
  METALLB_INGRESS_ADDR: "192.168.1.10"
