apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:QcwTs4kDzJRHkVEO2ejC7jjdAx+WspzHmWj6RrkMEvCHmm/nN9TqEuvWhbTwA4O/lGu8ykjmFle9ms+AYtaQ,iv:F8ypVOJAvRUkWZPpRwGtgLfi/gdNNt+Id44A7rbvadM=,tag:fO3UoVOtCh/xEE5a5JuOAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzd6g8hl928w3l8tch8vntwhmv6zxanspe3xg43z4sa08lx36yqsvty85u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z2plcWl5c2VRMHlzNHFl
            OVhzWDdVQWNZNXFqSmFvcm1MM0RsaUZvSVJBCmdqa2ZFTTNZa0o5aDFGWG9iNG5S
            M1hiU0JMTjNRVzc4REdZMEhDaFJ3blkKLS0tIGY1WGtHR0hjbmlnUk5EN21RMnJ1
            b0dVVFJ0R3VPeWdoYW5FSGo5VDlwa1UK06HRkCKpe2rOHSRSwA18MdfCZYOKCsjd
            uWJTeGwwJE4yeCpn+j7Q1rRAH0sF7sViMyVdRULQ3qLzAFgogdtbZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T22:13:13Z"
    mac: ENC[AES256_GCM,data:thGiMHKlRKX5t/k/FZggt+KbZrPCc8e2ekpV1i8zGMJiV0/Is/I+dH4IDg5jwh145MB0YmvXTT6gllci41HvWOIg3RZeJ+v7zxS7YKND+eslMHfEQnxK9t20wPxEJpciZK9B60HZnR70+zPx6dCrNey+4QeDFw+iKcCk4A7zVEY=,iv:+lBG9+/ll9XM9x7dIbhSCK1R8c+t1fseSy2zGNRKWUA=,tag:c/bVgGHmzXSrxTT6lG3kFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
