---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${NFS_STORAGECLASS_NAME}
  resources:
    requests:
      storage: 10Gi
